### PR TITLE
Fixed issue #9

### LINKED ISSUE #9: v1 and v2 generates different output
The output swagger is not identical for v1/v2.

### PR DESCRIPTION
**Pull request by joeljeffery**
Fix #9 - premature change of returnType to responseTypeAttr.Type @line 205

### CODE REVIEW

**Comment by wobba** [comment]
@joeljeffery can you pull my code from this morning and resolve the conflicts? Added separate sln/csproj for v2.

**Comment by joeljeffery** [comment]
Done!

**Comment by wobba** [comment]
Awesome work 😀

**Comment by joeljeffery** [comment]
Cheers!

**Pull request merged**
