### PR TITLE
.NET v4.x/Standard/Core with fixes

### PR DESCRIPTION
**Pull request by joeljeffery**
Fixed HttpRequestMessage issue for .NET Core/Standard.

### CODE REVIEW

**Comment by wobba** [comment]
@joeljeffery care to look at the merge conflict? If not I'll look at it later and try to resolve once I see the issues (currently on my phone)

**Comment by wobba** [comment]
And you know you can keep on committing to the same PR up until it's merged. Don't need a new PR 😁

**Comment by joeljeffery** [comment]
Learn something new every day ;)

I'll take a look at the merge conflicts... I think the compiler defs are throwing it off.

**Comment by wobba** [comment]
Appreciate it. If not I'll fix it and check both compile versions.

**Comment by joeljeffery** [comment]
Oooo......! You did some magic to support cases when the return type is an array. I'll fold that in and add commits to PR #8 :)

**Comment by joeljeffery** [comment]
Done!

**Comment by wobba** [comment]
Looks good, I’ll review and test with projects I have, and merge. Think I might even add some tests - which I should have done in the first place to validate the output. Awesome work!

**Comment by wobba** [comment]
@joeljeffery I see there is some differences in the output from v1 and v2, but don't have time to look at it right now. Created an issue so I won't forget #9.

**Pull request merged**
