### PR TITLE
Add support for Nullable<T>, List<T>, and annotating HttpRequestMessage

### PR DESCRIPTION
**Pull request by bherila**

### CODE REVIEW

**Comment by bherila** [comment]
@wobba this is still not working for top level types (request/response) that are collections, the generated type definitions end up containing the properties like Length, Count, etc. Any idea how to propagate the correct type through?

**Comment by wobba** [comment]
@bherila Can you post a sample class/function and I'll see if I can figure it out. Didn't actually test your code, but assume you did :)

**Comment by wobba** [comment]
@bherila what does your PR do? What case does it solve and what does it not solve?

**Comment by bherila** [comment]
It allows you to generate on APIs which contain lists and Nullable<T> 

e.g. "int?" which is `Nullable<int>` was not properly getting the "number" type out. With this PR, it works as expected.

```c#
[FunctionName(nameof(DirectAlertAdminImport))]
		[ResponseType(typeof(ApiRegistrations))]
		[HttpPost]
		public static HttpResponseMessage DirectAlertAdminImport(
			[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "dAdmin/import")] [FromBody]
			ApiRegistrations req, TraceWriter log)
		{
```
+
```c#
public class ApiRegistrations
	{
		public DirectAlertRegistration[] Registrations { get; set; }
	}

	[Table("custupdate")]
	public class DirectAlertRegistration
	{
		[Column("id"), Key] 
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int id { get; set; }

		[Column("AccountNumber")] public string AccountNumber { get; set; }
		[Column("AccountName")] public string AccountName { get; set; }
		[Column("ZipCode")] public string ZipCode { get; set; }
		[Column("CellPhone")] public string CellPhone { get; set; }
		[Column("HomePhone")] public string HomePhone { get; set; }
		[Column("WorkPhone")] public string WorkPhone { get; set; }
		[Column("Email")] public string Email { get; set; }
		[Column("Want_CellSMS")] public bool? Want_CellSMS { get; set; }
		[Column("Want_CellCall")] public bool? Want_CellCall { get; set; }
		[Column("Want_HomeCall")] public bool? Want_HomeCall { get; set; }
		[Column("Want_WorkCall")] public bool? Want_WorkCall { get; set; }
		[Column("Want_EmergencyEmail")] public bool? Want_EmergencyEmail { get; set; }
		[Column("Want_Email")] public bool? Want_Email { get; set; }
		[Column("CDate")] public DateTime Timestamp { get; set; }
		[Column("AltPhone")] public string AltPhone { get; set; }
		[Column("expiry")] public DateTime? Expiry { get; set; }
	}
```
turns into

```typescript
export interface ApiRegistrations {
    "registrations"?: Array<DirectAlertRegistration>;
}

export interface DirectAlertRegistration {
    "id"?: number;
    "accountNumber"?: string;
    "accountName"?: string;
    "zipCode"?: string;
    "cellPhone"?: string;
    "homePhone"?: string;
    "workPhone"?: string;
    "email"?: string;
    "wantCellSMS"?: boolean;
    "wantCellCall"?: boolean;
    "wantHomeCall"?: boolean;
    "wantWorkCall"?: boolean;
    "wantEmergencyEmail"?: boolean;
    "wantEmail"?: boolean;
    "timestamp"?: Date;
    "altPhone"?: string;
    "expiry"?: Date;
}

```

**Comment by wobba** [comment]
So, your question on top level types? Can you exemplify? Do you have a sample which fails for top level types?

**Comment by wobba** [comment]
@bherila I see you remove `if (parameter.ParameterType == typeof(HttpRequestMessage)) continue;`. What case is solved by keeping this? `HttpRequestMessage` is not a type per say, and should not be expanded.

Please add samples to the `Templates.cs` file to provide samples for the code you add. And need to ensure all existing cases still work.

**Comment by bherila** [comment]
The case is solved where the framework is not properly decoding my JSON objects and so instead, I am annotating the `HttpRequestMessage` with a new `[RequestType]` attribute, which I also included the source code to. I am open to another way of handling this however it doesn't seem like I can replace the `HttpRequestMessage` with the proper type in Azure Functions v1 :(

I will include some samples soon including the sample which fails for the top level types. Been a very hectic week thus far, thanks for your patience and the quick responses!

**Comment by wobba** [comment]
One option would be two versions/branches. Or `#if` compiler directives to solve both v1/2.

**Comment by wobba** [comment]
@bherila could you please pull in the latest code which support both v1/v2, and re-work the PR?

**Comment by bherila** [comment]
Unfortunately I don't have time to rework the PR right now. The work done here does significantly improve this package and I hope you'll consider adopting it in whatever way is useful to the community.  I am no longer using this package in favor of a Swashbuckle plugin for AzureFunctions which I created here: https://github.com/bherila/Swashbuckle.AspNetCore/tree/azure-functions

**Comment by wobba** [comment]
No problem. And swashbuckle is awesome. Just couldn't find a way for it to work directly with functions, and didn't want a shadow asp.net project just to get swagger. I'll try merge it myself and appreciate the PR 🙂

**Comment by bherila** [comment]
Thanks! Btw, pretty sure you don't really need asp.net except for the assemblies to get the annotations... I hear ya though. There are a lot of gotchas in generating these type definitions! I will keep monitoring this package and hope to be back soon 👍

**Comment by wobba** [comment]
I guess swashbuckle require mvc and routing to inject itself, which is missing for functions. I tried to dig a bit into it but gave up as hacking this one together was fairly quick. We'll see where everything goes 🙂

**Comment by bherila** [comment]
With my Swashbuckle integration you instantiate it statically. Look here: https://github.com/bherila/Swashbuckle.AspNetCore/blob/azure-functions/test/WebSites/FunctionApp/GenerateSwaggerFunction.cs

All the configuration is done in the HttpTrigger static function. It uses Microsoft.Extensions.DependencyInjection.

**Comment by wobba** [comment]
Ahhhhh.... very clever. Maybe I'll switch to this then 😃 Def will try it out when I have the time.

**Comment by bherila** [comment]
It does not work with netstandard1.x btw so that might be a blocker for you if you are using functions v1. Since functions v2 has reached GA and I have only just started using functions at all, this was not a blocker for me.

**Comment by bherila** [comment]
Plus I'm using my own local Swashbuckle packages while waiting on https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/912

**Comment by wobba** [comment]
I am using v1 due to other constraints - oh well :) My code works for me, and maybe the team will ensure Swagger just works for .Net in v1 and v2 one day.

**Comment by bherila** [comment]
Also @wobba if you want to play with my swashbuckle impl I have uploaded...

```
BH.Swashbuckle.AspNetCore.AzureFunctions.1.0.0
BH.Swashbuckle.AspNetCore.Annotations.4.0.0
BH.Swashbuckle.AspNetCore.SwaggerGen.4.0.0
BH.Swashbuckle.AspNetCore.Swagger.4.0.0
```

feel free to play with it if you like!

**Comment by wobba** [comment]
Thank you @bherila - just need to get some time and need to go into this again ;) Doing some mobile dev at the moment.

**Pull request closed without merging**
